name: ssh-mitm # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '4.0.0' # just for humans, typically '1.2+git' or '1.3.2'
license: GPL-3.0
website: https://docs.ssh-mitm.at
source-code: https://github.com/ssh-mitm/ssh-mitm
issues: https://github.com/ssh-mitm/ssh-mitm/issues
contact: support@ssh-mitm.at
title: SSH-MITM - ssh audits made simple
summary: man in the middle SSH Server for security audits and malware analysis # 79 char long summary
description: |
  Password and publickey authentication are supported and SSH-MITM is able to detect,
  if a user is able to login with publickey authentication on the remote server.
  This allows SSH-MITM to accept the same key as the destination server.

  If publickey authentication is not possible, the authentication will fall back to
  password-authentication.

  When publickey authentication is possible, a forwarded agent is needed to login
  to the remote server. In cases, when no agent was forwarded, SSH-MITM can rediredt
  the session to a honeypot.

icon: snap/gui/ssh-mitm.png
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: [amd64, arm64, armhf]

parts:
  ssh-mitm:
    # See 'snapcraft plugins'
    plugin: python
    source: .
apps:
  ssh-mitm:
    command: bin/ssh-mitm
    environment:
      PYTHONIOENCODING: utf-8
      PYTHONOPTIMIZE: 1
    plugs:
      - home
      - network
      - network-bind
      - ssh-keys
