name: ssh-mitm
base: core24
version: '5.0.1'
license: GPL-3.0-only
website: https://docs.ssh-mitm.at
source-code: https://github.com/ssh-mitm/ssh-mitm
issues: https://github.com/ssh-mitm/ssh-mitm/issues
contact: support@ssh-mitm.at
title: SSH-MITM - ssh audits made simple
summary: man in the middle SSH Server for security audits and malware analysis
description: |
  Password and publickey authentication are supported and SSH-MITM is able to detect,
  if a user is able to login with publickey authentication on the remote server.
  This allows SSH-MITM to accept the same key as the destination server.

  If publickey authentication is not possible, the authentication will fall back to
  password-authentication.

  When publickey authentication is possible, a forwarded agent is needed to login
  to the remote server. In cases, when no agent was forwarded, SSH-MITM can redirect
  the session to a honeypot.

icon: snap/gui/ssh-mitm.png
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:
  arm64:
  armhf:

parts:
  ssh-mitm:
    plugin: python
    source: .
    python-packages:
      - pip

apps:
  ssh-mitm:
    command: bin/ssh-mitm
    environment:
      PYTHONIOENCODING: utf-8
    plugs:
      - home
      - network
      - network-bind
      - ssh-keys
