# pylint: skip-file
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hostinput.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "hostinput.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0fhostinput.proto\x12\x0bHostBuffers"<\n\x0bHostMessage\x12-\n\x0binstruction\x18\x01 \x03(\x0b\x32\x18.HostBuffers.Instruction"\x17\n\x0bInstruction*\x08\x08\x02\x10\x80\x80\x80\x80\x02"\x1f\n\tHostBytes\x12\x12\n\nhoststring\x18\x04 \x01(\x0c".\n\rResizeMessage\x12\r\n\x05width\x18\x05 \x01(\x05\x12\x0e\n\x06height\x18\x06 \x01(\x05"\x1f\n\x07\x45\x63hoAck\x12\x14\n\x0c\x65\x63ho_ack_num\x18\x08 \x01(\x04:C\n\thostbytes\x12\x18.HostBuffers.Instruction\x18\x02 \x01(\x0b\x32\x16.HostBuffers.HostBytes:D\n\x06resize\x12\x18.HostBuffers.Instruction\x18\x03 \x01(\x0b\x32\x1a.HostBuffers.ResizeMessage:?\n\x07\x65\x63hoack\x12\x18.HostBuffers.Instruction\x18\x07 \x01(\x0b\x32\x14.HostBuffers.EchoAckB\x02H\x03'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "hostinput_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"H\003"
    _globals["_HOSTMESSAGE"]._serialized_start = 32
    _globals["_HOSTMESSAGE"]._serialized_end = 92
    _globals["_INSTRUCTION"]._serialized_start = 94
    _globals["_INSTRUCTION"]._serialized_end = 117
    _globals["_HOSTBYTES"]._serialized_start = 119
    _globals["_HOSTBYTES"]._serialized_end = 150
    _globals["_RESIZEMESSAGE"]._serialized_start = 152
    _globals["_RESIZEMESSAGE"]._serialized_end = 198
    _globals["_ECHOACK"]._serialized_start = 200
    _globals["_ECHOACK"]._serialized_end = 231
# @@protoc_insertion_point(module_scope)
