# pylint: skip-file
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transportinstruction.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "transportinstruction.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1atransportinstruction.proto\x12\x10TransportBuffers"\x8e\x01\n\x0bInstruction\x12\x18\n\x10protocol_version\x18\x01 \x01(\r\x12\x0f\n\x07old_num\x18\x02 \x01(\x04\x12\x0f\n\x07new_num\x18\x03 \x01(\x04\x12\x0f\n\x07\x61\x63k_num\x18\x04 \x01(\x04\x12\x15\n\rthrowaway_num\x18\x05 \x01(\x04\x12\x0c\n\x04\x64iff\x18\x06 \x01(\x0c\x12\r\n\x05\x63haff\x18\x07 \x01(\x0c\x42\x02H\x03'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "transportinstruction_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"H\003"
    _globals["_INSTRUCTION"]._serialized_start = 49
    _globals["_INSTRUCTION"]._serialized_end = 191
# @@protoc_insertion_point(module_scope)
