# pylint: skip-file
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: userinput.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "userinput.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0fuserinput.proto\x12\rClientBuffers">\n\x0bUserMessage\x12/\n\x0binstruction\x18\x01 \x03(\x0b\x32\x1a.ClientBuffers.Instruction"\x17\n\x0bInstruction*\x08\x08\x02\x10\x80\x80\x80\x80\x02"\x19\n\tKeystroke\x12\x0c\n\x04keys\x18\x04 \x01(\x0c".\n\rResizeMessage\x12\r\n\x05width\x18\x05 \x01(\x05\x12\x0e\n\x06height\x18\x06 \x01(\x05:G\n\tkeystroke\x12\x1a.ClientBuffers.Instruction\x18\x02 \x01(\x0b\x32\x18.ClientBuffers.Keystroke:H\n\x06resize\x12\x1a.ClientBuffers.Instruction\x18\x03 \x01(\x0b\x32\x1c.ClientBuffers.ResizeMessageB\x02H\x03'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "userinput_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"H\003"
    _globals["_USERMESSAGE"]._serialized_start = 34
    _globals["_USERMESSAGE"]._serialized_end = 96
    _globals["_INSTRUCTION"]._serialized_start = 98
    _globals["_INSTRUCTION"]._serialized_end = 121
    _globals["_KEYSTROKE"]._serialized_start = 123
    _globals["_KEYSTROKE"]._serialized_end = 148
    _globals["_RESIZEMESSAGE"]._serialized_start = 150
    _globals["_RESIZEMESSAGE"]._serialized_end = 196
# @@protoc_insertion_point(module_scope)
