#!/bin/bash

# set APPDIR when running directly from the AppDir:
if [ -z $APPDIR ]; then
    export APPDIR=$(readlink -f $(dirname "$0"))
fi

# check if an environment file exists and load it
if [ -f "$APPDIR/environment.sh" ]; then
    source $APPDIR/environment.sh
fi

# start the python application and pass arguments
exec $APPDIR/python/bin/python3 $APPDIR/startapp.py $@